config/routes.rb
Rails.application.routes.draw do
  # ユーザー用
  # URL /customers/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }


  scope module: :public do
      root to: "homes#top"
      get "about" => "homes#about"

      resources :users, only: [:show, :edit, :update] do
       resource :relationships, only: [:create, :destroy]
       get "followings" => "relationships#followings", as: "followings"
       get "followers" => "relationships#followers", as: "followers"
       collection do
         get "search"
       end
     end
      get "/users_index" => "users#index", as: "users"
      get "users/:id/unsubscribe" => "users#unsubscribe", as: "unsubscribe"
      patch "users/:id/withdraw" => "users#withdraw", as: "withdraw"

      resources :reviews do
        resource :favorites, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy] do
       end
      end

      resources :rooms, only: [:create, :show]
      resources :messages, only: [:create]
    end


  namespace :admin do
      root to: "homes#top"
      resources :users, only: [:index, :show, :edit, :update] do
         collection do
           get "search"
         end
       end
      resources :reviews, only: [:index, :show, :edit, :update, :destroy] do
         resources :comments, only: [:destroy]
       end
    end

  devise_scope :user do
    post "users/guest_sign_in" => "public/sessions#new_guest", as: "guest"
    get "/users" => "public/registrations#new"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @params = params
    if params[:address]
      if params[:price_min] == "" || params[:price_max] == ""
        @reviews = Review.where(["name LIKE(?) and address LIKE(?) and sauna_area  LIKE(?) and sauna_temperature LIKE(?) and loryu_type LIKE(?) and aufguss LIKE(?) and water_area LIKE(?) and water_temperature LIKE(?)", "%#{params[:name]}%", "%#{params[:address]}%", "%#{params[:sauna_area]}%", "%#{params[:sauna_temperature]}%", "%#{params[:loryu_type]}%", "%#{params[:aufguss]}%", "%#{params[:water_area]}%", "%#{params[:water_temperature]}%"]).page(params[:page]).order(created_at: :desc)

      else
        @reviews = Review.where(["name LIKE(?) and address LIKE(?) and sauna_area  LIKE(?) and sauna_temperature LIKE(?) and loryu_type LIKE(?) and aufguss LIKE(?) and water_area LIKE(?) and water_temperature LIKE(?)", "%#{params[:name]}%", "%#{params[:address]}%", "%#{params[:sauna_area]}%", "%#{params[:sauna_temperature]}%", "%#{params[:loryu_type]}%", "%#{params[:aufguss]}%", "%#{params[:water_area]}%", "%#{params[:water_temperature]}%"])
        .where(price: (params[:price_min])..(params[:price_max])).page(params[:page]).order(created_at: :desc)
      end
    else
      @reviews = Review.page(params[:page]).order(created_at: :desc)
    end
  end

  def show
    @review = Review.find(params[:id])
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:notice] = "レビューを更新しました"
      redirect_to admin_review_path(@review)
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "投稿を削除しました"
    redirect_to admin_reviews_path
  end

 private
   def review_params
     params.require(:review).permit(:name, :address, :sauna_area, :sauna_temperature, :loryu_type, :aufguss, :water_temperature, :water_area, :chair_count, :price, :body, :sauna_time, :congestion, :sauna_image)
   end
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/views/admin/reviews/_search.html.erb
<div class="col-4 card mt-5 mb-5" style="height:920px;">
  <%= form_with  url: admin_reviews_path, method: :get  do |f| %>

  <p class="mt-3 text-center border border-dark about_sub">検索フォーム</p>
  <p class="mt-5"><%= f.label "施設名:", class: "about_sub" %>
  <%= f.text_field :name, value: @params["name"], class: 'col-12' %></p>

  <p class="mb-0"><%= f.label "住所:", class: "about_sub" %></p>
  <p><%= f.text_field :address , value: @params["address"], class: 'col-12' %></p>

   <p class="mb-0 mt-4"><%= f.label "金額:", class: "about_sub" %></p>
   <div class= "col-12 text-right">
     <p>￥<%= f.text_field :price_min , value: @params["price_min"], class: 'mr-2' %>円より高い</p>
     <p>￥<%= f.text_field :price_max, value: @params["price_max"], class: 'mr-2' %>円より安い</P>
   </div>

  <p style="margin-top:50px; text-align: center;" class="border border-dark about_sub">詳細な条件検索</p>

  <p class="mb-3 mt-4"><%= f.label "サウナの広さ:", class: 'mr-3 about_sub' %>
    <%= f.radio_button :sauna_area, 0, {checked: @params["sauna_area"] == "0"}%>
    <%= f.label :sauna_area, "狭い", {value: 0, style: "display: inline-block;", class: 'mr-3'}%>
    <%= f.radio_button :sauna_area, 1, {checked: @params["sauna_area"] == "1" }%>
    <%= f.label :sauna_area, "普通", {value: 1, style: "display: inline-block;", class: 'mr-3'} %>
    <%= f.radio_button :sauna_area, 2, {checked: @params["sauna_area"] == "2" }%>
    <%= f.label :sauna_area, "広い", {value: 2, style: "display: inline-block;"} %>
  </p>

  <p class="mb-0"><%= f.label "サウナの温度:", class: 'mr-2 about_sub' %>
    <%= f.radio_button :sauna_temperature, 0, {checked: @params["sauna_temperature"] == "0" }%>
    <%= f.label :sauna_temperature, "〜40℃", {value: 0, style: "display: inline-block;", class: 'mr-4'} %>
    <%= f.radio_button :sauna_temperature, 1, {checked: @params["sauna_temperature"] == "1" }%>
    <%= f.label :sauna_temperature, "65℃〜70℃", {value: 1, style: "display: inline-block;"} %></br>
  </p>
  <div class="text-right mr-4">
    <%= f.radio_button :sauna_temperature, 2, {checked: @params["sauna_temperature"] == "2" }%>
    <%= f.label :sauna_temperature, "80℃〜90℃", {value: 2, style: "display: inline-block;", class: 'mr-3'} %>
    <%= f.radio_button :sauna_temperature, 3, {checked: @params["sauna_temperature"] == "3" }%>
    <%= f.label :sauna_temperature, "100℃以上", {value: 3, style: "display: inline-block;"} %>
  </div>
  <p><%= f.label "ロウリュの種類:",class: 'mt-3 mb-0 about_sub' %></p>
  <%= f.radio_button :loryu_type, 0, {checked: @params["loryu_type"] == "0" }%>
  <%= f.label :loryu_type, "オートロウリュ", {value: 0, style: "display: inline-block;"} %>
  <%= f.radio_button :loryu_type, 1, {checked: @params["loryu_type"] == "1" }%>
  <%= f.label :loryu_type, "セルフロウリュ", {value: 1, style: "display: inline-block;"} %>
  <%= f.radio_button :loryu_type, 2, {checked: @params["loryu_type"] == "2" }%>
  <%= f.label :loryu_type, "なし", {value: 2, style: "display: inline-block;"} %>
  </p>


  <p><%= f.label "アウフグース有無:", class: 'mt-3 mr-4 about_sub' %>
     <%= f.radio_button :aufguss, 0, {checked: @params["aufguss"] == "0" }%>
     <%= f.label :aufguss, "あり", {value: 0, style: "display: inline-block;",class: "mr-3"} %>
     <%= f.radio_button :aufguss, 1, {checked: @params["aufguss"] == "1" }%>
     <%= f.label :aufguss, "なし", {value: 1, style: "display: inline-block;"} %>
  </p>

  <p><%= f.label "水風呂の広さ:", class: 'mb-0 mr-3 about_sub' %>
     <%= f.radio_button :water_area, 0, {checked: @params["water_area"] == "0" }%>
     <%= f.label :water_area, "狭い", {value: 0, style: "display: inline-block;",class: "mr-2"} %>
     <%= f.radio_button :water_area, 1, {checked: @params["water_area"] == "1" }%>
     <%= f.label :water_area, "普通", {value: 1, style: "display: inline-block;",class: "mr-2"} %>
     <%= f.radio_button :water_area, 2, {checked: @params["water_area"] == "2" }%>
      <%= f.label :water_area, "広い", {value: 2, style: "display: inline-block;"} %>
  </p>

  <p><%= f.label "水風呂の温度:", class: 'mb-0 about_sub' %></p>
   <div class="mb-4">
    <%= f.radio_button :water_temperature, 0, {checked: @params["water_temperature"] == "0" }%>
    <%= f.label :water_temperature, "18℃〜24℃", {value: 0, style: "display: inline-block;",class: "mr-3"} %>
    <%= f.radio_button :water_temperature, 1, {checked: @params["water_temperature"] == "1" }%>
    <%= f.label :water_temperature, "11℃〜17℃", {value: 1, style: "display: inline-block;",class: "mr-3"} %>
    <%= f.radio_button :water_temperature, 2, {checked: @params["water_temperature"] == "2" }%>
    <%= f.label :water_temperature, "10℃以下", {value: 2, style: "display: inline-block;"} %>
   </div>

  <div class="text-right">
   <%= f.submit "この条件で検索", class: "btn btn-info"%>
  </div>
  <% end %>
</div>

app/views/admin/reviews/edit.html.erb
<% if @review.errors.any? %>
  <%= review.errors.count %>件のエラーが発生しました
  <ul>
    <% review.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class='container'>
  <div class='row'>
    <div class="col-sm-12">
      <h2>管理者/レビュー編集</h2>
        <%= form_with model: @review, url: admin_review_path(@review.id), local: true ,method: :patch  do |f| %>
       <div class=" card container shadow rounded-top mb-5 mt-5">
       <div class="form-group row mt-4">
           <%= f.label "施設名:", class: 'col-md-4 text-right mr-3 about_sub' %>
          <%= f.text_field :name, class: "form-control name col-md-5" %>
       </div>

       <div class="form-group row">
        <%= f.label "住所:", class: 'col-md-4 text-right mr-3 about_sub' %>
        <%= f.text_field :address, placeholder: "◯◯県◯◯市/郡◯◯/区/町/村/番地", class: "form-control name col-md-5" %>
       </div>

       <div class="form-group row">
        <%= f.label "利用料金:",class: 'col-md-4 text-right mr-3 about_sub' %>
        <%= f.text_field :price, placeholder: "大人1名あたり", class: "form-control name col-md-2 text-right" %>円
       </div>

       <div class="form-group row">
        <%= f.label "サウナの広さ:", class: 'col-md-4 text-right mr-3 about_sub' %>
        <%= f.collection_radio_buttons :sauna_area, Review.sauna_areas_i18n, :first , :last, class: "form-control name" %>
       </div>

       <div class="form-group row">
         <%= f.label "サウナの温度:", class: 'col-md-4 text-right mr-3 about_sub'%>
         <%= f.collection_radio_buttons :sauna_temperature, Review.sauna_temperatures_i18n, :first , :last, class: "form-control name" %>
       </div>

       <div class="form-group row">
         <%= f.label "ロウリュの種類:", class: 'col-md-4 text-right mr-3 about_sub' %>
         <%= f.collection_radio_buttons :loryu_type, Review.loryu_types_i18n, :first , :last, class: "form-control name" %>
       </div>

       <div class="form-group row">
         <%= f.label "アウフグース有無:", class: 'col-md-4 text-right mr-3 about_sub' %>
         <%= f.collection_radio_buttons :aufguss, Review.aufgusses_i18n, :first , :last, class: "form-control name" %>
       </div>

        <div class="form-group row">
         <%= f.label "水風呂の広さ:", class: 'col-md-4 text-right mr-3 about_sub' %>
         <%= f.collection_radio_buttons :water_area, Review.water_areas_i18n, :first , :last, class: "form-control name" %>
       </div>

       <div class="form-group row">
         <%= f.label "水風呂の温度:", class: 'col-md-4 text-right mr-3 about_sub' %>
         <%= f.collection_radio_buttons :water_temperature, Review.water_temperatures_i18n, :first , :last, class: "form-control name" %>
       </div>

       <div class="form-group row">
         <%= f.label "チェアの数:", class: 'col-md-4 text-right mr-3 about_sub' %>
         <%= f.collection_radio_buttons :chair_count, Review.chair_counts_i18n, :first , :last, class: "form-control name" %>
       </div>

       <div class="form-group row">
         <%= f.label "行った時間帯:", class: 'col-md-4 text-right mr-3 about_sub' %>
         <%= f.collection_radio_buttons :sauna_time, Review.sauna_times_i18n, :first , :last, class: "form-control name" %>
       </div>

       <div class="form-group row">
         <%= f.label "混雑状況:", class: 'col-md-4 text-right mr-3 about_sub' %>
         <%= f.collection_radio_buttons :congestion, Review.congestions_i18n, :first , :last, class: "form-control name" %>
       </div>

       <div class="form-group row">
         <%= f.label "サウナ写真:", class: "col-md-4 text-right about_sub" %>
         <%= f.file_field :sauna_image, class: "form-control-file user_image col-md-8", accept: 'image/*' %>
        </div>
       </div>
       <div class="form-group row">
         <%= f.label "感想・詳細など", class: "about_sub"%>
         <%= f.text_area :body, size: "5x6", class: "form-control name" %>
        </div>

       <div class="form-group row">

        <div id="post_raty">
         <%= f.label :evaluation, "星評価：" %>
         <%= f.hidden_field :evaluation, id: :review_star %>
        </div>
        <%#= javascript_include_tag 'jquery.raty.js' %>
        <script>
          // scriptファイルをどのidの部分に配置するかを指定
          // let elem = document.querySelector('#post_raty');
          $(function(){
           console.log($('#post_raty'));
           $('#post_raty').empty();
           $('#post_raty').raty({
           //星画像の指定などのオプションをここに記述,
           size     : 36,
           starOff:  '<%= asset_path('star-off.png') %>',
           starOn : '<%= asset_path('star-on.png') %>',
           starHalf: '<%= asset_path('star-half.png') %>',
           scoreName: 'review[evaluation]',
           half: true,
           });
          })

           // raty(elem,opt);
         </script>
        </div>

        <div>
         <p class="text-right"><%= f.submit "編集する", class: 'btn btn-info' %></p>
        </div>
     <% end %>
    </div>
  </div>
</div>

app/views/admin/reviews/index.html.erb
<div><%= flash[:notice] %></div>

<h1 class="x active mx-auto">管理者/レビューリスト︎︎</h1>
 <div class="container">
  <div class="row">
   <div class="col-8">
    <% if @reviews.present? %>
     <% @reviews.each do |review| %>
     <div class="card container shadow rounded-top mb-5 mt-5 p-0">
      <div class="card-body row">
       <%= image_tag review.get_sauna_image(700,700), class: "sauna_image" %>
       <p class="col-12"><%= link_to review.name,admin_review_path(review.id), class: "review_name" %></p>

       <p class="col-12">住所:
       　　<%= review.address %></p>

       <p class="col-12">大人一人当たりの金額:
       　　¥<%= review.price %>円</p>

       <p class="col-12 sub">[総合評価]</p>
       <p class="col-6" id="post_raty<%= review.id %>"></p>
       </div>
         <p class="col-6"><%= image_tag review.user.get_profile_image(50,50), class: "rounded-circle" %></br>
         投稿者:<%= review.user.name %>さん</p>
       </div>
        <script>
          $(function(){
           console.log($('#post_raty<%= review.id %>'));
          $('#post_raty<%= review.id %>').empty();
          $('#post_raty<%= review.id %>').raty({
            //星画像の指定などのオプションをここに記述,
           size     : 36,
           starOff:  '<%= asset_path('star-off.png') %>',
           starOn : '<%= asset_path('star-on.png') %>',
           starHalf: '<%= asset_path('star-half.png') %>',
           score: <%= review.evaluation %>,
           readOnly: true,
           half: true,
            });
           })
        </script>
     <% end %>
    <% else %>
  <!--検索がヒットしなかった場合-->
   <p>検索結果はありません</p>
    <% end %>
     <%= paginate @reviews %>
   </div>
  <%= render 'admin/reviews/search'%>
</div>
</div>

app/views/admin/reviews/show.html.erb
<div><%= flash[:notice] %></div>

<div class ="container">
 <div class="row">
  <div class="col-9 card mr-3 mb-5 mt-5 p-0">
  <%=image_tag@review.get_sauna_image(700,700), class: "sauna_image"%>

   <p class="review_name2 ml-4 mt-4 mb-5">管理者/︎<%=@review.name%>の詳細レビュー</p>
 <div class="row">
  <div class="card col-5 border border-danger ml-5 mr-3 shadow rounded" style="background-color:#FAF0E6">

    <h3 class="sauna mt-3">サウナ🔥</h3>

    <div class="row">
     <p class= "s col-5 ml-2 mb-2 mt-3">サウナ広さ:</p>
     <h4 class="sauna_area col-5 mt-3"><%= @review.sauna_area_i18n %></h4>
    </div>

     <div class="row">
     <p class= "s col-4 ml-2 mb-4 mt-3">サウナ温度:</p>
     <h5 class="sauna_ondo col-6 mt-3"><%=@review.sauna_temperature_i18n%></h5>
    </div>

     <div class="row">
     <p class= "s col-4 ml-2 mb-2">ロウリュ:</p>
     <h4 class="sauna_area col-7"><%=@review.loryu_type_i18n%></h4>
    </div>

    <div class="row">
     <p class= "s col-5 ml-2 mb-4 mt-3">アウフグース:</p>
     <h4 class="sauna_area col-5 mt-3 mb-4"><%=@review.aufguss_i18n%></h4>
    </div>


  </div>
  <div class=" card col-5 border border-info ml-3 mr-3 shadow rounded" style="background-color:#E0FFFF;">

   <h3 class="mizu mt-3">水風呂💧</h3>

   <div class="row">
     <p class= "s col-5 ml-2 mb-2 mt-4 mb-4">水風呂広さ:</p>
     <h4 class="sauna_area col-5 mt-4 mb-4"><%=@review.water_area_i18n%></h4>
    </div>

   <div class="row">
     <p class= "s col-4 ml-2 mb-4 mt-5">水風呂温度:</p>
     <h4 class="mizu_ondo col-6 mt-5"><%=@review.water_temperature_i18n%></h4>
    </div>

   </div>
  </div>

   <div class="row">
     <p class= "about_sub col-4 ml-5 mb-4 mt-5 text-right">住所:</p>
     <h4 class=" col-7 mt-5"><%= @review.address %></h4>
   </div>

    <div class="row mr-5">
     <p class= "about_sub col-12 ml-2 mb-4 text-right">料金:
     ￥<%= @review.price %>円</p>
    </div>

  <div class="card container">
   <div class="row mt-3">
   <p class= "col-2 about_sub text-right">椅子の数:</p>
   <p class="col-2"><%=@review.chair_count_i18n%></p>
   <p class= "col-2 about_sub" style="font-size:14px;">入浴した時間帯:</p>
   <p class= "col-2"><%=@review.sauna_time_i18n%></p>
   <p class= "col-2 about_sub text-right">人の多さ:</p>
   <p class= "col-2"><%=@review.congestion_i18n%></p>
    </div>
  </div>

   <strong class= "ml-5 mb-2 mt-4 about_sub">[メモ]</strong>
   <div class="card rounded mb-5 mx-auto" style="width:80%;">
    <p class="mb-2 ml-4" style="font-size:20px;"><%=@review.body%></p>
   </div>

  <div id="post_raty<%= @review.id %>" class="text-right mr-3">総合評価：</div>
   <script>
   $(function(){
    console.log($('#post_raty<%= @review.id %>'));
     $('#post_raty<%= @review.id %>').empty();
     $('#post_raty<%= @review.id %>').raty({
      //星画像の指定などのオプションをここに記述,
       size     : 36,
       starOff:  '<%= asset_path('star-off.png') %>',
       starOn : '<%= asset_path('star-on.png') %>',
       starHalf: '<%= asset_path('star-half.png') %>',
       score: <%= @review.evaluation %>,
       readOnly: true,
       half: true,
        });
       })
   </script>

 <div>
    <%= link_to '編集', edit_admin_review_path(@review), class: "btn btn-sm btn-success" %>
    <%= link_to '削除', admin_review_path(@review), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%>
 </div>


   <p class="ml-5 mt-5">コメント一覧:</p>
    <div class= "comment_area card mx-auto mb-4" style="width:80%">
      <% if @review.comments.present? %>
       <% @review.comments.each do |review_comment| %>
        <table class="container border border-end">
         <tbody class="row mt-3">
          <tr class="col-6">
           <td class="col-2"><%= image_tag review_comment.user.get_profile_image(40,40), class: "mb-3 rounded-circle" %>
            <td class="col-10">ユーザー名：<%= link_to admin_user_path(review_comment.user_id) do %>
                <%= review_comment.user.name %>
                <% end %>
            </td>
           </td>
          </tr>
          <tr class="col-6 mt-3">
             <td>
               <%= review_comment.comment %>
             </td>
           <td>
             <%= link_to "Destroy", admin_review_comment_path(review_comment.review, review_comment), class: "btn btn-sm btn-danger", method: :delete %>
           </td>
          </tr>
         </tbody>
        </table>
        <% end %>
       <% else %>
        <p class="text-center mt-5 mb-5">まだコメントがありません</p>
        <% end %>
    </div>
</div>
  <div class=" col-2  ml-3 mb-5 mt-5">
  <p>ユーザー情報
   <%=link_to admin_user_path(@review.user)do%>
    <%=image_tag@review.user.get_profile_image(100,100), class: "rounded-circle"%><br>
    <%=@review.user.name%></p>
   <%end%>
     フォロー:　　<%=@review.user.followings.count%>人</br>
     フォロワー:　<%= @review.user.followers.count %>人
  </div>
 </div>
</div>