config/routes.rb
Rails.application.routes.draw do
  # ユーザー用
  # URL /customers/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }


  scope module: :public do
      root to: "homes#top"
      get "about" => "homes#about"

      resources :users, only: [:show, :edit, :update] do
       resource :relationships, only: [:create, :destroy]
       get "followings" => "relationships#followings", as: "followings"
       get "followers" => "relationships#followers", as: "followers"
       collection do
         get "search"
       end
     end
      get "/users_index" => "users#index", as: "users"
      get "users/:id/unsubscribe" => "users#unsubscribe", as: "unsubscribe"
      patch "users/:id/withdraw" => "users#withdraw", as: "withdraw"

      resources :reviews do
        resource :favorites, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy] do
       end
      end

      resources :rooms, only: [:create, :show]
      resources :messages, only: [:create]
    end


  namespace :admin do
      root to: "homes#top"
      resources :users, only: [:index, :show, :edit, :update] do
         collection do
           get "search"
         end
       end
      resources :reviews, only: [:index, :show, :edit, :update, :destroy] do
         resources :comments, only: [:destroy]
       end
    end

  devise_scope :user do
    post "users/guest_sign_in" => "public/sessions#new_guest", as: "guest"
    get "/users" => "public/registrations#new"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :profile_image, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :view_counts, dependent: :destroy
  # has_many :comment_favorites, dependent: :destroy
  # relationshipsはアソシエーションが繋がっているテーブル名、class_nameは実際のモデルの名前、foreign_keyは外部キーとして何を持つかを表している。
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧にフォロー、フォロワーの表示ができる、＠user.followeingsとすることで自分がフォローした人表示できる
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  def active_for_authentication?
    super && (is_deleted == false)
  end

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpeg")
      profile_image.attach(io: File.open(file_path), filename: "no_image.jpeg", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.guest
    find_or_create_by!(email: "test@test.com") do |user|
       user.password = SecureRandom.alphanumeric(10) + [*"a".."z"].sample(1).join + [*"0".."9"].sample(1).join
       user.name = "ゲストユーザー"
       user.phone_number = "12345678901"
     end
  end

  validates :name, presence: true
  validates :phone_number, presence: true, length: { is: 11 }, uniqueness: true, numericality: { only_integer: true }
  validates :introduction, length: { maximum: 200 }
  validates :profile_image, blob: { content_type: ["image/png", "image/jpg", "image/jpeg"], size_range: 1..5.megabytes }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!, :search

  def index
    @users = @q.result(distinct: true)
  end

  def search
    # params[:q]のqには検索フォームに入力した値が入る/検索の処理をしている
    @q = User.ransack(params[:q])
  end

  def show
    @user = User.find(params[:id])
    @reviews = Review.where(user_id: [@user.id]).page(params[:page]).order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "ユーザー情報を更新しました"
      redirect_to admin_user_path(@user.id)
    else
      render "edit"
    end
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :phone_number, :is_deleted)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<h2 class="text-center pt-4 mb-4">管理者/ユーザー編集</h2>
<div class='container' style="height:500px;">
  <div class='row'>
    <div class="col mx-auto">
    <% if @user.errors.any? %>
     <%= @user.errors.count %>件のエラーが発生しました
      <ul>
       <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
      </ul>
    <% end %>
     <%= form_with model: @user, url: admin_user_path(@user.id), local: true ,method: :patch do |f| %>
      <div class="form-group col-6 mx-auto">
        <%= f.label "名前" %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
      <div class="form-group col-6 mx-auto">
        <%= f.label "施設の写真" %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group col-6 mx-auto">
        <%= f.label "自己紹介" %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>

       <div class="form-group col-6 mx-auto">
       <p>ユーザーステータス</p>
        <%= f.radio_button :is_deleted, 0, checked: true %>有効
        <%= f.radio_button :is_deleted, 1 %>退会
       </div>

      <div class="form-group col-6 mx-auto">
        <%= f.submit "編集する", class: 'btn btn-secondary' %>
      </div>
    <% end %>
     </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="user_index">
 <h1 class="text-center pt-5 about_sub">管理者/ユーザーリスト</h1>
  <%= search_form_for @q do |f| %>
    <!--name_contは、あいまい検索を指定-->
    <p class="text-center">ユーザー検索：<%= f.text_field :name_cont, class: "mt-5 mb-5" %>
    <%= f.submit "検索", class: "ml-3 mr-3 btn btn-sm btn-info" %>
    </p>
  <% end %>
<!--検索結果-->
 <% if @users.present? %>
  <!--検索がヒットした場合-->
 <table class='table table-borderless container mb-0'>
  <tbody class="row ml-5">
      <% @users.each do |user| %>
       <tr class="card rounded-circle col-3 mr-4 ml-5 mb-4" style="width:200px; height:280px;">
        <td class="mx-auto"><%= image_tag user.get_profile_image(100,100), class: "rounded-circle mt-3" %></td>
        <td class="text-center pb-0"><%= link_to user.name, admin_user_path(user.id), class: "text-dark" %>さん</td>
        <td class="text-center">フォロー:　<%=user.followings.count%>人</br>
          フォロワー:　<%= user.followers.count %>人</td>
       </tr>
      <% end %>
 <% else %>
  <!--検索がヒットしなかった場合-->
  <p>検索結果はありません</p>
<% end %>
  </tbody>
 </table>
</div>

app/views/admin/users/show.html.erb
<div><%= flash[:notice] %></div>

<div class="container">
 <div class="row">
  <div class="col-4 mr-3 mb-5 mt-5">
   <h4 class=" text-center">管理者/ユーザー情報</h4>
    <p class="col-12 text-center mt-3"><%= image_tag @user.get_profile_image(150,150), class: "rounded-circle" %></p>

    <div class="row mt-3">
     <p class="col-6 text-right">ユーザー名:</p>
     <p class="col-6"><%= @user.name%></p>
    </div>

    <% if @user.introduction? %>
       <p class="mt-3">自己紹介</p>
      <div class="card">
       <p><%= @user.introduction %></p>
       </div>
    <% end %>

    <div class="row mt-3" style="margin-left:80px;">
     <% if @user.is_deleted %>
      ユーザーステータス：<p class="text-Secondary">退会</p>
     <% else %>
      ユーザーステータス：<p class="text-success">有効</p>
     <% end %>
    </div>
    <div class="container mt-3">
      <div class="row">
          <%= link_to edit_admin_user_path(@user), class: "btn btn-sm btn-info btn-block  mb-3" do %>
           編集<i class="fas fa-user-cog"></i>
          <% end %>
      </div>
     </div>
   </div>

    <div class="col-7 ml-4 mb-5 mt-5">
        <h3 class="about_sub"><%= @user.name %>さんの投稿</h3>
     <% if @reviews.present? %>
      <% @reviews.each do |review| %>
       <div class="card container shadow rounded-top mb-5 mt-5 p-0">
         <div class="card-body row">
          <%= image_tag review.get_sauna_image(700,700), class: "sauna_image" %>
          <p class="col-12"><%= link_to review.name,admin_review_path(review.id), class: "review_name" %></p>

          <p class="col-12">住所:
         　　<%= review.address %>
          </p>

          <p class="col-12">大人一人当たりの金額:
       　　¥<%= review.price %>円
          </p>

         [総合評価]
          <p class="col-6 mt-3 ml-4" id="post_raty<%= review.id %>"></p>
           <script>
            $(function(){
              console.log($('#post_raty<%= review.id %>'));
            $('#post_raty<%= review.id %>').empty();
            $('#post_raty<%= review.id %>').raty({
              //星画像の指定などのオプションをここに記述,
               size     : 36,
               starOff:  '<%= asset_path('star-off.png') %>',
               starOn : '<%= asset_path('star-on.png') %>',
               starHalf: '<%= asset_path('star-half.png') %>',
               score: <%= review.evaluation %>,
               readOnly: true,
                half: true,
                  });
                 })
           </script>
         </div>
           <p class="col-6"><%= image_tag review.user.get_profile_image(50,50), class: "rounded-circle" %></br>
             投稿者:<%= review.user.name %>さん
           </p>
       </div>
        <% end %>
        <%= paginate @reviews %>
       <% else %>
        <p class="card text-center" style="height:300px; padding-top:100px;">
          表示する内容がありません。</br>
          新しく投稿するか、ユーザーをフォローして</br>
          サウナのレビューを見てみよう！
        </p>
       <% end %>
   </div>
  </div>
</div>