config/routes.rb
Rails.application.routes.draw do
  # ユーザー用
  # URL /customers/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }


  scope module: :public do
      root to: "homes#top"
      get "about" => "homes#about"

      resources :users, only: [:show, :edit, :update] do
       resource :relationships, only: [:create, :destroy]
       get "followings" => "relationships#followings", as: "followings"
       get "followers" => "relationships#followers", as: "followers"
       collection do
         get "search"
       end
     end
      get "/users_index" => "users#index", as: "users"
      get "users/:id/unsubscribe" => "users#unsubscribe", as: "unsubscribe"
      patch "users/:id/withdraw" => "users#withdraw", as: "withdraw"

      resources :reviews do
        resource :favorites, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy] do
       end
      end

      resources :rooms, only: [:create, :show]
      resources :messages, only: [:create]
    end


  namespace :admin do
      root to: "homes#top"
      resources :users, only: [:index, :show, :edit, :update] do
         collection do
           get "search"
         end
       end
      resources :reviews, only: [:index, :show, :edit, :update, :destroy] do
         resources :comments, only: [:destroy]
       end
    end

  devise_scope :user do
    post "users/guest_sign_in" => "public/sessions#new_guest", as: "guest"
    get "/users" => "public/registrations#new"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer style='background-color:#42403e'>
  <div class='container' style='height:100px'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p class= 'd-flex align-items-center mb-0 text-white' style='height:100px'>© 2022 souunect8 Co., Ltd.</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light head_foot">
    <div class="container">
          <!--管理側でのheader-->
           <% if admin_signed_in? %>
             <%= link_to "Sauunect", admin_root_path, class: "a" %>
           <% else %>
             <%= link_to "Sauunect", root_path, class: "a" %>
           <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation"><!--レスポンシブ対応の展開ボタン-->
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %> <!--管理者側がログイン中か確認する-->
                  <li><%= link_to "レビュー管理", admin_reviews_path, class: 'nav-link' %></li><!--レビュー一覧へのリンク-->
                  <li><%= link_to "ユーザー管理", admin_users_path, class: 'nav-link' %></li><!--会員一覧へのリンク-->
                  <li><%= link_to "ログアウト", destroy_admin_session_path, class: 'nav-link', method: :delete %></li><!--ログアウトへのリンク-->
              <% end %>
              <!--顧客側ログイン中のheader-->
              <% if user_signed_in? %> <!--顧客側がログイン中か確認する-->
                  <li><%= link_to "マイページ", user_path(current_user), class: 'nav-link bi bi-person-lines-fill' %></li><!--マイページへのリンク-->
                  <li><%= link_to "投稿一覧", reviews_path, class: 'nav-link bi bi-book-half' %></li><!--レビュー一覧へのリンク-->
                  <li><%= link_to "ユーザー", users_path, class: 'nav-link bi bi-people-fill' %></li><!--ユーザー一覧へのリンク-->
                  <li><%= link_to "ログアウト", destroy_user_session_path, class: 'nav-link bi bi-door-open-fill', method: :delete %></li><!--ログアウトへのリンク-->
              <!--顧客側のheader-->
              <% else %><!--非ログイン時に表示するheader-->
                <% unless admin_signed_in? %>
                  <li><%= link_to "saunnectとは？", about_path, 'data-turbolinks': false, class: 'nav-link' %></li><!--aboutへのリンク-->
                  <li><%= link_to "新規登録", new_user_registration_path, class: 'nav-link bi bi-person-plus-fill' %></li><!--新規登録へのリンク-->
                  <li><%= link_to "ログイン", new_user_session_path, class: 'nav-link bi bi-box-arrow-in-right' %></li><!--ログイン画面へのリンク-->
                  <li><%= link_to 'ゲスト', guest_path, method: :post, class: 'nav-link bi bi-wrench-adjustable' %></li>
                <% end %>
              <% end %>
            </ul>
        </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sounnect</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css"/>
    <script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kalam:wght@700&family=Kiwi+Maru&family=Permanent+Marker&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="css/5-13.css">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
    <%= yield %>
    </main>
    <span id="back">
      <%= link_to "#" do %><%= image_tag 'arrow.jpg', :size => '50x50' %><% end %>
    </span>
    <%= render 'layouts/footer' %>
  </body>
</html>